### ISSUE TITLE
Parameter guide

### ISSUE THREAD

**Issue by tatesmithstudio** [mzucker/maptrace#3]
Hi,

I am using your project to "vectorize" some images I am generating with edge detection. I want to vectorize these files cleanly as you have done in your examples but I am not getting results I am happy with. I think in part this has to do with the parameters I am choosing. Can you point me to the place where the parameters are defined? Alternatively if you have some tips towards successfully doing this I would love to hear it. 

See the attached for an example image and output. It seems to me that your work here would be able to achieve my goals pretty easily. The first image attached here is the input and the second is the output.

![RETRY](https://user-images.githubusercontent.com/63619177/92308574-8264d300-ef96-11ea-941b-8763aacac662.png)
<img width="1049" alt="Screen Shot 2020-09-05 at 4 40 11 PM" src="https://user-images.githubusercontent.com/63619177/92308581-885ab400-ef96-11ea-9459-f2d564451de0.png">

Best regards and thanks for creating this wonderful little piece of code.

**Comment by mzucker** [comment]
First of all, I inverted your input image – the program expects dark outlines and light fills. 

Then I ran with the following parameters: -e 0.1 -f erode:box,3

The -e 0.1 specifies not to simplify boundaries between regions too much.
The -f erode:box,3 says to take the dark lines and thicken them by 3 pixels before tracing

Then I added -r to get random colors. Here's input and output:

![tate](https://user-images.githubusercontent.com/3287580/92312691-2481bc80-ef91-11ea-8102-7cc0085f6308.png)

![tate-output](https://user-images.githubusercontent.com/3287580/92312697-382d2300-ef91-11ea-9f51-a0020915f484.png)
